version: "3.7"

services:
  web:
    # image: getumbrel/umbrel-nostr-relay
    build: ./ui
    user: "1000:1000"
    restart: on-failure
    environment:
      RELAY_HOST: "relay"
      RELAY_PORT: "8080"
      RELAY_PROXY_HOST: "relay-proxy"
      RELAY_PROXY_PORT: "80"
    ports:
      - 3000:3000

  relay:
    image: getumbrel/nostr-rs-relay:0.8.1@sha256:a6c857aecd4964bf058ec5c3c0fea95e0d87ed0cc789f2140f96de108e5515ec
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ${PWD}/data/relay/config.toml:/app/config.toml
      - ${PWD}/data/relay/db:/app/db

  relay-proxy:
    # image: getumbrel/umbrel-nostr-relay-proxy
    build: ./relay-proxy
    user: "1000:1000"
    restart: on-failure
    environment:
      RELAY_HOST: "relay"
      RELAY_PORT: "8080"
    volumes:
      - ${PWD}/data/relay-proxy:/app/data
    depends_on:
      - relay