name: Build and publish Docker image on tag

on:
  push:
    tags:
      - 'v*.*.*'

env:
  DOCKER_CLI_EXPERIMENTAL: enabled

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - directory: 'ui'
            name: 'umbrel-nostr-relay'
          - directory: 'relay-proxy'
            name: 'umbrel-nostr-relay-proxy'
    steps:
      - name: Set VERSION
        run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker buildx action
        uses: docker/setup-buildx-action@v2

      - name: Run Docker buildx
        working-directory: ${{ matrix.service.directory }}
        run: |
          docker buildx build \
          --tag ${{ secrets.DOCKER_HUB_USER }}/${{ matrix.service.name }}:$VERSION \
          --platform linux/amd64,linux/arm64 \
          --push .